
version: '1.0'

networks:
  demo-datn:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    restart: always
    networks: 
      - demo-datn
    container_name: zookeeper
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_USER

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    networks:
      - demo-datn
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER