apiVersion: v1
kind: Pod
metadata:
  name: order_service_pod
  labels:
    name: order_service_pod
    app: order
spec:
  containers:
    - name: order_service
      image: yfangvjoker/order-service:s1
      port: 
        - containerPort: 8080