apiVersion: v1
kind: PersistentVolume
metadata:
  name: product-volume
  labels:
    type: local
    app: productdb
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/productdb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: productdb-volume-claim
  labels:
    app: productdb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: productdb
  labels:
    app: productdb
spec:
  type: NodePort
  selector:
    app: productdb
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productdb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: productdb
  template:
    metadata:
      labels:
        app: productdb
    spec:
      containers:
        - name: productdb
          image: postgres
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: product-secret
          volumeMounts:
            - name: productdbdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: productdbdata
          persistentVolumeClaim:
            claimName: productdb-volume-claim