"""init migration

Revision ID: a7fd15fd1df0
Revises: 
Create Date: 2024-10-12 12:28:08.729913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7fd15fd1df0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prod_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prod_name', sa.String(length=255), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('prod_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prod_type_id'], ['prod_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('prod_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('prod_type')
    # ### end Alembic commands ###
